language: node_js

node_js:
- "4"

install:
- sudo apt-get install swig
- git clone https://github.com/mozilla/sphinxbase
- cd sphinxbase
- ./autogen.sh
- ./configure
- make
- sudo make install
- cd ..
- git clone https://github.com/mozilla/pocketsphinx
- cd pocketsphinx
- ./autogen.sh
- ./configure
- make
- sudo make install
- cd ..
- npm install
